[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = "$free $icon"
format_alt = "$free / $total $icon"

[[block]]
block = "sound"
format = " $icon $output_name{ $volume|} "
[block.mappings]
"alsa_output.pci-0000_00_1f.3.analog-stereo" = "Speakers"
"alsa_output.usb-Logitech_A50-00.analog-stereo" = "Headset"

[[block]]
block = "cpu"
format = "$utilization $icon"

[icons]
icons = "emoji"
[icons.overrides]
volume_muted = "󰝟 "
volume = [
    " ",
    " ",
    " "
]
headphones = "󰋎"
cpu = " "
disk_drive = " "
